# How to install

- Using conda
    
        conda install numpy

- Using pip   
    
        pip install numpy
        
**You can install any python library using these commands by replacing numpy with your necessary library name.**

# Using library


In [1]:
import numpy as np
print(np.__version__)

1.18.2


In [298]:
%%time
l = [i for i in range(0, 100000)]

for i in l:
    l[i] = l[i]/2

Wall time: 41 ms


In [299]:
%%time

l = [i for i in range(0, 100000)]

l = np.array(l) / 2

Wall time: 20 ms


# NumPy 

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Also, it is a Linear Algebra Library for Python, the reason it is so important for Machine Learning with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. 

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: 

- Data Structure 
- Vectors,Arrays,Matrices 
- Append, delete, split, etc
- Number generation
- Array Attributes and Methods
- Selection, Indexing
- NumPy Operations

Let's start.


## Data Structure
Numpy array a combination of a memory address, a data type, a shape, and strides:

- The data pointer indicates the memory address of the first byte in the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.
- The data type or dtype pointer describes the kind of elements that are contained within the array,
- The shape indicates the shape of the array, and
- The strides are the number of bytes that should be skipped in memory to go to the next element. If your strides are (10,1), you need to proceed one byte to get to the next column and 10 bytes to locate the next row.


<img src='img/ds.png' width='650'>

In [187]:
a = np.array([[1, 2, 3],
              [2, 3, 4],
              [3, 4, 5],
              [4, 5, 6]])

print(f"data -> {a.data}")
print(f"data type -> {a.dtype}")
print(f"shape -> {a.shape}")
print(f"strides -> {a.strides}")

data -> <memory at 0x000002685FAA72D0>
data type -> int32
shape -> (4, 3)
strides -> (12, 4)


## Creating NumPy Arrays, Vector, Matrices

Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

In [188]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [189]:
np.array(my_list)


array([1, 2, 3])

In [190]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Append, delete, split

In [232]:
a = np.array([[0, 1, 2]])
b = np.array([[3, 4, 5], [7, 8, 9]])

print(a.shape, b.shape)
np.append(a, b)

(1, 3) (2, 3)


(array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([ 0,  1,  2, 11]))

In [ ]:
np.append(a, 11)

In [233]:
new = np.append(a, b, axis=0)
new

array([[0, 1, 2],
       [3, 4, 5],
       [7, 8, 9]])

In [231]:
c = np.array([[0, 1, 2], [6, 7, 8]])

print(b.shape, c.shape)
np.append(b, c, axis=1)

(2, 3) (2, 3)


array([[3, 4, 5, 0, 1, 2],
       [7, 8, 9, 6, 7, 8]])

In [241]:
# delete
print(a)
np.delete(a, 1)

[[0 1 2]]


array([0, 2])

In [236]:
np.delete(new, 1, 0)

array([[0, 1, 2],
       [7, 8, 9]])

In [238]:
np.delete(new, 1, 1)

array([[2],
       [5],
       [9]])

In [264]:
a = np.arange(8.0)
print(a)
# np.split(a, 2)
np.split(a, [2])

[0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1.]), array([2., 3., 4., 5., 6., 7.])]

In [273]:
print(b)
np.split(b, [1])

[[3 4 5]
 [7 8 9]]


[array([[3, 4, 5]]), array([[7, 8, 9]])]

In [275]:
print(b)
np.split(b, [1], axis=1)

[[3 4 5]
 [7 8 9]]


[array([[3],
        [7]]),
 array([[4, 5],
        [8, 9]])]

# Number generation

There are lots of built-in ways to generate Arrays


- ### arange
Return evenly spaced values within a given interval.

In [158]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

- ### linspace
Return evenly/equally spaced numbers over a specified interval.

In [157]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

- ### zeros and ones
Generate arrays of zeros or ones

In [150]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [149]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [152]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [151]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- ### eye
Creates an identity matrix

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- ### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [146]:
np.random.rand(2)

array([0.68749537, 0.27656258])

In [147]:
np.random.rand(2,2)

array([[0.37354026, 0.54341094],
       [0.8098802 , 0.60351633]])

- ### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [145]:
np.random.randn(2)

array([1.99592974, 1.58306485])

In [13]:
np.random.randn(2,2)

array([[ 0.33521944,  1.97322462],
       [-2.06546814, -0.39724454]])

- ### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [142]:
np.random.randint(1,100,2)

array([[65, 96, 11, 90, 40, 48],
       [51, 70, 62, 65, 10, 81]])

In [144]:
np.random.randint(1,100,(3,3))

array([[82, 68, 98],
       [70, 95, 98],
       [98, 90, 88]])

># Task 
- Create 2x3 matrices using **rand**
- Create 2x3 matrices using **randn**
- Append them 

In [141]:
# task code

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:



- ### Shape

In [95]:
# Vector
arr = np.arange(25)
arr.shape

(25,)

- ### Reshape
Returns an array containing the same data with a new shape.

In [98]:
arr = np.arange(25)
print(arr.shape)
arr = arr.reshape(5,5)
print(arr.shape)

(25,)
(5, 5)


In [99]:
# arr.reshape(-1,1)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

- ### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [109]:
ranarr = np.random.randint(0, 50, 4)
ranarr

array([13,  7,  3, 29])

In [110]:
ranarr.max(), ranarr.argmax() 

(29, 3)

In [116]:
# index for 2d array
print(arr)
np.unravel_index(arr.argmax(), arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(4, 4)

In [111]:
ranarr.min(), ranarr.argmin()

(3, 2)

- ### dtype

You can also grab the data type of the object in the array:

In [22]:
arr.dtype

dtype('int32')

> # Task
- Create a vector/array with shape (16,) 
- Reshape it into 4X4 metrices
- Find max value with index

In [ ]:
# task code

# NumPy Indexing and Selection

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number.

In [167]:
#Creating sample array
arr = np.random.randint(0, 101, 20)
arr

array([ 60,  94,  93,  42,  64,  40,   3,  37,  32,  90,  50,  37,  85,
        32,  36,  38, 100,   5,  65,  14])

In [168]:
#Selecting a value at an index
arr[0]

60

In [169]:
#values in a range
arr[1:5]

array([94, 93, 42, 64])

In [170]:
d2 = np.arange(16)
d2 = d2.reshape(4,4)
print(d2)
d2[:,-2:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [171]:
#values in a range
arr[1::2]

array([94, 42, 40, 37, 90, 37, 32, 38,  5, 14])

In [172]:
print(d2)
d2[:,::2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [173]:
# select and create new array
new = arr[2:6]
new 

array([93, 42, 64, 40])

In [174]:
new[-2:] = 1
new

array([93, 42,  1,  1])

In [175]:
d2[:,::2] = 0
d2

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15]])

In [176]:
# conditional selecing
arr[(arr>70)]

array([ 94,  93,  90,  85, 100])

In [183]:
d2[d2==0] = 1
d2

array([[ 1,  1,  1,  3],
       [ 1,  5,  1,  7],
       [ 1,  9,  1, 11],
       [ 1, 13,  1, 15]])

In [184]:
# conditional selecing
arr[(arr>50) & (arr<100)]

array([60, 94, 93, 90, 85, 65])

> # Task
- Create a 1D array 
- Show values in between 10 and 20
- Create a 2D array (4, 4)
- Replace values greater than 5 to 0

In [ ]:
# task code

# NumPy Operations

Let's see some examples:

In [29]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [32]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [33]:
#Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [34]:
# sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [35]:
#  log
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Thank you!

### Resources:
- https://cs231n.github.io/python-numpy-tutorial/#numpy
- https://www.geeksforgeeks.org/numpy-in-python-set-1-introduction/
- https://github.com/rougier/numpy-tutorial
